//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoMVC.ProdutoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjetoMVC.ProdutoServiceReference.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisponivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjetoMVC.ProdutoServiceReference.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disponivel {
            get {
                return this.DisponivelField;
            }
            set {
                if ((this.DisponivelField.Equals(value) != true)) {
                    this.DisponivelField = value;
                    this.RaisePropertyChanged("Disponivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdutoId {
            get {
                return this.ProdutoIdField;
            }
            set {
                if ((this.ProdutoIdField.Equals(value) != true)) {
                    this.ProdutoIdField = value;
                    this.RaisePropertyChanged("ProdutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ProjetoWCF")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjetoMVC.ProdutoServiceReference.Produto[] ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobrenomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjetoMVC.ProdutoServiceReference.Produto[] Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sobrenome {
            get {
                return this.SobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobrenomeField, value) != true)) {
                    this.SobrenomeField = value;
                    this.RaisePropertyChanged("Sobrenome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutoServiceReference.IProdutoService")]
    public interface IProdutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAll", ReplyAction="http://tempuri.org/IProdutoService/FindAllResponse")]
        ProjetoMVC.ProdutoServiceReference.Produto[] FindAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAll", ReplyAction="http://tempuri.org/IProdutoService/FindAllResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto[]> FindAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Find", ReplyAction="http://tempuri.org/IProdutoService/FindResponse")]
        ProjetoMVC.ProdutoServiceReference.Produto Find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Find", ReplyAction="http://tempuri.org/IProdutoService/FindResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> FindAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/New", ReplyAction="http://tempuri.org/IProdutoService/NewResponse")]
        ProjetoMVC.ProdutoServiceReference.Produto New(ProjetoMVC.ProdutoServiceReference.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/New", ReplyAction="http://tempuri.org/IProdutoService/NewResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> NewAsync(ProjetoMVC.ProdutoServiceReference.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Update", ReplyAction="http://tempuri.org/IProdutoService/UpdateResponse")]
        ProjetoMVC.ProdutoServiceReference.Produto Update(ProjetoMVC.ProdutoServiceReference.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Update", ReplyAction="http://tempuri.org/IProdutoService/UpdateResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> UpdateAsync(ProjetoMVC.ProdutoServiceReference.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/DeleteId", ReplyAction="http://tempuri.org/IProdutoService/DeleteIdResponse")]
        ProjetoMVC.ProdutoServiceReference.Produto DeleteId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/DeleteId", ReplyAction="http://tempuri.org/IProdutoService/DeleteIdResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> DeleteIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Delete", ReplyAction="http://tempuri.org/IProdutoService/DeleteResponse")]
        ProjetoMVC.ProdutoServiceReference.Produto Delete(ProjetoMVC.ProdutoServiceReference.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Delete", ReplyAction="http://tempuri.org/IProdutoService/DeleteResponse")]
        System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> DeleteAsync(ProjetoMVC.ProdutoServiceReference.Produto produto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoServiceChannel : ProjetoMVC.ProdutoServiceReference.IProdutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoServiceClient : System.ServiceModel.ClientBase<ProjetoMVC.ProdutoServiceReference.IProdutoService>, ProjetoMVC.ProdutoServiceReference.IProdutoService {
        
        public ProdutoServiceClient() {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProjetoMVC.ProdutoServiceReference.Produto[] FindAll() {
            return base.Channel.FindAll();
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto[]> FindAllAsync() {
            return base.Channel.FindAllAsync();
        }
        
        public ProjetoMVC.ProdutoServiceReference.Produto Find(int id) {
            return base.Channel.Find(id);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> FindAsync(int id) {
            return base.Channel.FindAsync(id);
        }
        
        public ProjetoMVC.ProdutoServiceReference.Produto New(ProjetoMVC.ProdutoServiceReference.Produto produto) {
            return base.Channel.New(produto);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> NewAsync(ProjetoMVC.ProdutoServiceReference.Produto produto) {
            return base.Channel.NewAsync(produto);
        }
        
        public ProjetoMVC.ProdutoServiceReference.Produto Update(ProjetoMVC.ProdutoServiceReference.Produto produto) {
            return base.Channel.Update(produto);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> UpdateAsync(ProjetoMVC.ProdutoServiceReference.Produto produto) {
            return base.Channel.UpdateAsync(produto);
        }
        
        public ProjetoMVC.ProdutoServiceReference.Produto DeleteId(int id) {
            return base.Channel.DeleteId(id);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> DeleteIdAsync(int id) {
            return base.Channel.DeleteIdAsync(id);
        }
        
        public ProjetoMVC.ProdutoServiceReference.Produto Delete(ProjetoMVC.ProdutoServiceReference.Produto produto) {
            return base.Channel.Delete(produto);
        }
        
        public System.Threading.Tasks.Task<ProjetoMVC.ProdutoServiceReference.Produto> DeleteAsync(ProjetoMVC.ProdutoServiceReference.Produto produto) {
            return base.Channel.DeleteAsync(produto);
        }
    }
}
